# Generated by Django 4.2 on 2024-04-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='token',
            new_name='url_hash',
        ),
    ]
