# Generated by Django 4.2 on 2024-04-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_token_customuser_url_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='url_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Хэш'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
