# Generated by Django 4.2 on 2024-04-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.RenameField(
            model_name='option',
            old_name='servey',
            new_name='survey',
        ),
    ]
