# Generated by Django 4.2 on 2024-04-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_options_rename_servey_option_survey'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='option',
            table='option',
        ),
        migrations.AlterModelTable(
            name='survey',
            table='survey',
        ),
    ]
