# Generated by Django 4.2 on 2024-04-19 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_alter_option_table_alter_survey_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='user',
        ),
        migrations.AddField(
            model_name='option',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='options', to=settings.AUTH_USER_MODEL),
        ),
    ]
