# Generated by Django 4.2 on 2024-04-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_option_user_option_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
    ]
